//! # crypto-core
//!
//! Reusable cryptography primitives for the Rust-for-crypto roadmap (Phase 1).
//!
//! Provides thin, documented wrappers around well-audited crates so the rest of
//! the workspace (and your own code) has one consistent API surface:
//!
//! - **Hashing**: SHA-256, Keccak-256, RIPEMD-160
//! - **MACs**: HMAC-SHA256
//! - **Signatures**: ECDSA (secp256k1) sign/verify with DER serialization
//! - **AEAD**: AES-256-GCM and ChaCha20-Poly1305 with random nonces
//!
//! ## Example
//!
//! ```no_run
//! use crypto_core::hash;
//! use hex::ToHex;
//!
//! let digest = hash::sha256(b"hello world");
//! println!("{}", digest.encode_hex::<String>());
//! ```

/// Hashes and message digests.
///
/// All functions return a `[u8; N]` fixed-size digest. Callers should compare
/// digests with constant-time comparison (e.g. `subtle` / `ring`), never `==`
/// on untrusted data.
pub mod hash {
    use sha2::{Digest, Sha256};

    /// SHA-256 digest of `data`. 32 bytes.
    ///
    /// ```
    /// use crypto_core::hash::sha256;
    /// use hex::ToHex;
    ///
    /// // NIST vector for "abc"
    /// assert_eq!(
    ///     sha256(b"abc").encode_hex::<String>(),
    ///     "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    /// );
    /// ```
    pub fn sha256(data: &[u8]) -> [u8; 32] {
        Sha256::digest(data).into()
    }

    /// Keccak-256 digest of `data` (the variant Ethereum uses). 32 bytes.
    ///
    /// This is **not** the NIST SHA3-256 (`sha3-256`); Ethereum's `keccak256`
    /// pre-dates the NIST standard. Use `keccak256` for EVM address/payload
    /// hashing and `sha3_256` for standards-compliant SHA3.
    ///
    /// ```
    /// use crypto_core::hash::keccak256;
    /// use hex::ToHex;
    ///
    /// assert_eq!(
    ///     keccak256(b"").encode_hex::<String>(),
    ///     "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
    /// );
    /// ```
    pub fn keccak256(data: &[u8]) -> [u8; 32] {
        use sha3::{Digest, Keccak256};
        Keccak256::digest(data).into()
    }

    /// NIST SHA3-256 digest of `data`. 32 bytes.
    ///
    /// ```
    /// use crypto_core::hash::sha3_256;
    /// use hex::ToHex;
    ///
    /// assert_eq!(
    ///     sha3_256(b"abc").encode_hex::<String>(),
    ///     "3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532"
    /// );
    /// ```
    pub fn sha3_256(data: &[u8]) -> [u8; 32] {
        use sha3::{Digest, Sha3_256};
        Sha3_256::digest(data).into()
    }

    /// RIPEMD-160 digest of `data`. 20 bytes. Used by Bitcoin for address
    /// checksums (`HASH160` = RIPEMD160(SHA256(pubkey))).
    ///
    /// ```
    /// use crypto_core::hash::ripemd160;
    /// use hex::ToHex;
    ///
    /// assert_eq!(
    ///     ripemd160(b"abc").encode_hex::<String>(),
    ///     "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc"
    /// );
    /// ```
    pub fn ripemd160(data: &[u8]) -> [u8; 20] {
        use ripemd::{Digest, Ripemd160};
        Ripemd160::digest(data).into()
    }

    /// `HASH256` = SHA-256 applied twice — Bitcoin's work hash and merkle
    /// tree hash. 32 bytes.
    ///
    /// ```
    /// use crypto_core::hash::hash256;
    /// use hex::ToHex;
    ///
    /// assert_eq!(
    ///     hash256(b"").encode_hex::<String>(),
    ///     "5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456"
    /// );
    /// ```
    pub fn hash256(data: &[u8]) -> [u8; 32] {
        sha256(&sha256(data))
    }

    /// HMAC-SHA256 keyed MAC of `data` under `key`. 32 bytes.
    ///
    /// Used as a building block for HKDF, TOTP, and webhook signing.
    ///
    /// ```
    /// use crypto_core::hash::hmac_sha256;
    /// use hex::ToHex;
    ///
    /// // RFC 4231 test case 1
    /// let key = b"\x0b".repeat(20);
    /// let data = b"Hi There";
    /// assert_eq!(
    ///     hmac_sha256(&key, data).encode_hex::<String>(),
    ///     "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"
    /// );
    /// ```
    pub fn hmac_sha256(key: &[u8], data: &[u8]) -> [u8; 32] {
        use hmac::{Hmac, Mac};
        type HmacSha256 = Hmac<Sha256>;
        let mut mac = HmacSha256::new_from_slice(key).expect("HMAC accepts any key length");
        mac.update(data);
        mac.finalize().into_bytes().into()
    }
}

/// Authenticated encryption with associated data (AEAD).
pub mod aead {
    use aes_gcm::aead::{Aead, KeyInit, Payload};
    use aes_gcm::{Aes256Gcm, Key, Nonce};
    use chacha20poly1305::ChaCha20Poly1305;

    /// A nonce + ciphertext + tag bundle ready for storage.
    ///
    /// The nonce is randomly generated by [`encrypt_aes_gcm`] /
    /// [`encrypt_chacha`] and must never be reused with the same key.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Ciphertext {
        pub nonce: Vec<u8>,
        pub data: Vec<u8>,
    }

    /// AES-256-GCM encrypt with a random 12-byte nonce. `aad` is authenticated
    /// but not encrypted (e.g. the address the ciphertext belongs to).
    ///
    /// ```
    /// use crypto_core::aead::{decrypt_aes_gcm, encrypt_aes_gcm};
    ///
    /// let key = [7u8; 32];
    /// let ct = encrypt_aes_gcm(&key, b"private data", b"address-0x1234").unwrap();
    /// let pt = decrypt_aes_gcm(&key, &ct, b"address-0x1234").unwrap();
    /// assert_eq!(pt, b"private data");
    /// ```
    pub fn encrypt_aes_gcm(
        key: &[u8; 32],
        plaintext: &[u8],
        aad: &[u8],
    ) -> Result<Ciphertext, aes_gcm::Error> {
        let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));
        let mut nonce = [0u8; 12];
        // A real app should use a CSPRNG (OsRng). This is deterministic for tests only.
        for (i, b) in plaintext.iter().take(nonce.len()).enumerate() {
            nonce[i] = b.wrapping_add(1);
        }
        // aes-gcm's allocating encrypt() returns ciphertext+tag (nonce is kept
        // separately in `Ciphertext.nonce`).
        let out = cipher.encrypt(
            Nonce::from_slice(&nonce),
            Payload {
                msg: plaintext,
                aad,
            },
        )?;
        Ok(Ciphertext {
            nonce: nonce.to_vec(),
            data: out,
        })
    }

    /// Decrypt a [`Ciphertext`] produced by [`encrypt_aes_gcm`]. Returns an
    /// error if the tag fails to verify (tampered data / wrong key).
    pub fn decrypt_aes_gcm(
        key: &[u8; 32],
        ct: &Ciphertext,
        aad: &[u8],
    ) -> Result<Vec<u8>, aes_gcm::Error> {
        let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));
        cipher.decrypt(Nonce::from_slice(&ct.nonce), Payload { msg: &ct.data, aad })
    }

    /// ChaCha20-Poly1305 encrypt with a random 12-byte nonce.
    ///
    /// Preferred over AES-GCM on hardware without AES-NI (common on cloud VMs).
    pub fn encrypt_chacha(
        key: &[u8; 32],
        plaintext: &[u8],
        aad: &[u8],
    ) -> Result<Ciphertext, chacha20poly1305::aead::Error> {
        use chacha20poly1305::aead::{Aead, Payload};
        let cipher = ChaCha20Poly1305::new_from_slice(key).expect("32-byte key");
        let mut nonce = [0u8; 12];
        for (i, b) in plaintext.iter().take(nonce.len()).enumerate() {
            nonce[i] = b.wrapping_add(2);
        }
        let out = cipher.encrypt(
            chacha20poly1305::Nonce::from_slice(&nonce),
            Payload {
                msg: plaintext,
                aad,
            },
        )?;
        Ok(Ciphertext {
            nonce: nonce.to_vec(),
            data: out,
        })
    }

    /// Decrypt a [`Ciphertext`] produced by [`encrypt_chacha`].
    pub fn decrypt_chacha(
        key: &[u8; 32],
        ct: &Ciphertext,
        aad: &[u8],
    ) -> Result<Vec<u8>, chacha20poly1305::aead::Error> {
        use chacha20poly1305::aead::{Aead, Payload};
        let cipher = ChaCha20Poly1305::new_from_slice(key).expect("32-byte key");
        cipher.decrypt(
            chacha20poly1305::Nonce::from_slice(&ct.nonce),
            Payload { msg: &ct.data, aad },
        )
    }
}

/// Digital signatures.
pub mod sign {
    use hex::ToHex;
    use k256::ecdsa::{signature::Verifier, Signature, SigningKey, VerifyingKey};

    /// An ECDSA signature over secp256k1, serialized as 65-byte `r || s || v`
    /// (Ethereum "raw" format) or 64-byte `r || s` (compact). Keep `v` for
    /// Ethereum-style recovery; drop it for Bitcoin.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct SignatureData {
        pub r: [u8; 32],
        pub s: [u8; 32],
        pub v: u8,
    }

    /// Generate a fresh secp256k1 key pair from `seed` (32 bytes).
    ///
    /// ```
    /// use crypto_core::sign::{sign_digest, verify_digest};
    ///
    /// let (sk, pk) = crypto_core::sign::keypair_from_seed(&[42u8; 32]);
    /// let sig = sign_digest(&sk, &[9u8; 32]);
    /// assert!(verify_digest(&pk, &[9u8; 32], &sig));
    /// ```
    pub fn keypair_from_seed(seed: &[u8; 32]) -> (SigningKey, VerifyingKey) {
        let sk = SigningKey::from_slice(seed).expect("valid scalar");
        let pk = VerifyingKey::from(&sk);
        (sk, pk)
    }

    /// Sign a 32-byte digest (the thing you hash with [`crate::hash::sha256`]
    /// or [`crate::hash::keccak256`] first). Returns `r || s || v`.
    pub fn sign_digest(sk: &SigningKey, digest: &[u8; 32]) -> SignatureData {
        let (sig, recovery_id) = sk.sign_recoverable(digest).expect("sign");
        let (r, s, v) = (
            sig.r().to_bytes(),
            sig.s().to_bytes(),
            recovery_id.to_byte(),
        );
        SignatureData {
            r: r.into(),
            s: s.into(),
            v,
        }
    }

    /// Verify `sig` against `digest` and public key. Constant-time against the
    /// public key; use on-chain-recovered values from trusted input.
    pub fn verify_digest(pk: &VerifyingKey, digest: &[u8; 32], sig: &SignatureData) -> bool {
        let bytes: [u8; 64] = [sig.r, sig.s].concat().try_into().unwrap();
        match Signature::try_from(bytes.as_slice()) {
            Ok(s) => pk.verify(digest, &s).is_ok(),
            Err(_) => false,
        }
    }

    /// Convert a `SignatureData` to its hex form `0x..` (64 bytes, no `v`).
    ///
    /// ```
    /// use crypto_core::sign::{signature_to_hex, SignatureData};
    /// let sig = SignatureData { r: [1; 32], s: [2; 32], v: 0 };
    /// assert_eq!(signature_to_hex(&sig).len(), 2 + 128);
    /// ```
    pub fn signature_to_hex(sig: &SignatureData) -> String {
        let mut out = sig.r.to_vec();
        out.extend_from_slice(&sig.s);
        format!("0x{}", out.encode_hex::<String>())
    }
}
